import pandas as pd
from main.models import *

data = pd.read_csv('/Users/johnny/Documents/perio_score/pssite/main/predict_tool/_target_example.csv', header=0)
for i in range(len(data)):
    curr_data=data.iloc[i,:]
    curr_rec=PatientInfo(Race_white=curr_data['Race_white'], Race_black=curr_data['Race_black'], Race_asian=curr_data['Race_asian'], Race_native=curr_data['Race_native'], Race_multiracial=curr_data['Race_multiracial'], Sex_female=curr_data['Sex_female'], Language_ENG=curr_data['Language_ENG'], Insurance_Cash=curr_data['Insurance_Cash'], Insurance_Private=curr_data['Insurance_Private'], Insurance_Medicaid=curr_data['Insurance_Medicaid'], Insurance_Ryan_White=curr_data['Insurance_Ryan_White'], AgeBaseline=curr_data['AgeBaseline'], Med1=curr_data['Med1'], Med2=curr_data['Med2'], Med3=curr_data['Med3'], Med4=curr_data['Med4'], Med5=curr_data['Med5'], Med6=curr_data['Med6'], Med7=curr_data['Med7'], Med8=curr_data['Med8'], Med9=curr_data['Med9'], Med10=curr_data['Med10'], Med11=curr_data['Med11'], Med12=curr_data['Med12'], CRA=curr_data['CRA'], Radiographs=curr_data['Radiographs'], Tobacco=curr_data['Tobacco'], Alcohol=curr_data['Alcohol'], RecDrugs=curr_data['RecDrugs'], Preg999t=curr_data['Preg999t'], ASA=curr_data['ASA'], DMFT=curr_data['DMFT'], DMFS=curr_data['DMFS'], Teeth=curr_data['Teeth'], PerioDxCal=curr_data['PerioDxCal'], PlaqueIdx=curr_data['PlaqueIdx'], BOP=curr_data['BOP'], BoneLoss=curr_data['BoneLoss'], BL_URQ=curr_data['BL_URQ'], BL_LRQ=curr_data['BL_LRQ'], BL_ULQ=curr_data['BL_ULQ'], BL_LLQ=curr_data['BL_LLQ'], BL_VERT=curr_data['BL_VERT'], BL_MaxPct=curr_data['BL_MaxPct'], Calc_URQ=curr_data['Calc_URQ'], Calc_LRQ=curr_data['Calc_LRQ'], Calc_ULQ=curr_data['Calc_ULQ'], Calc_LLQ=curr_data['Calc_LLQ'], RFG1=curr_data['RFG1'], RFG2=curr_data['RFG2'], RFG3=curr_data['RFG3'], RFG4=curr_data['RFG4'], RFG5=curr_data['RFG5'], RFG6=curr_data['RFG6'], RFG7=curr_data['RFG7'], RFG8=curr_data['RFG8'], RFL1=curr_data['RFL1'], RFL2=curr_data['RFL2'], RFL3=curr_data['RFL3'], RFL4=curr_data['RFL4'], RFL5=curr_data['RFL5'], RFL6=curr_data['RFL6'], RFL7=curr_data['RFL7'], RFL8=curr_data['RFL8'], RFL9=curr_data['RFL9'], RFL10=curr_data['RFL10'], DentalHealth=curr_data['DentalHealth'], PainLevel=curr_data['PainLevel'], Chewing=curr_data['Chewing'], Speaking=curr_data['Speaking'], SelfImage=curr_data['SelfImage'], AnxietyYest=curr_data['AnxietyYest'], AnxietyToday=curr_data['AnxietyToday'], ClenchGrind=curr_data['ClenchGrind'], GumTrouble=curr_data['GumTrouble'], BrushFreq=curr_data['BrushFreq'], FlossFreq=curr_data['FlossFreq'], Denture=curr_data['Denture'], SRPSxPerio=curr_data['SRPSxPerio'], OralSx=curr_data['OralSx'], Trauma=curr_data['Trauma'], OralCancer=curr_data['OralCancer'], TMJ=curr_data['TMJ'], Ortho=curr_data['Ortho'], PerioDx=curr_data['PerioDx'], PerioDx_new=curr_data['PerioDx_new'], StudyId=curr_data['StudyId'])
    curr_rec.save()





